name: Deploy to Dev EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        known_hosts: "optional"

    - name: Adding Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    # Frontend deployment (FIXED: No duplicate rsync)
    - name: Deploy Frontend
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
          ./frontend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/crynk-frontend/

    # Backend deployment  
    - name: Deploy Backend
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
          ./backend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/crynk-backend/

    # Restart services
    - name: Restart Services
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl restart crynk-frontend && sudo systemctl restart crynk-backend"
